services:
  db:
    image: timescale/timescaledb-ha:pg15.14-ts2.21.3-oss
    container_name: ais-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ais
      POSTGRES_PASSWORD: aispass
      POSTGRES_DB: ais
    ports:
      - "5432:5432"
    volumes:
      - ./db-data:/home/postgres/pgdata
      - ./db/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 10
